server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_01?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123123
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
  application:
    name: binbin-service-resume
eureka:
  client:
    service-url: # EurekaServer 路径
      defaultZone: http://binbinCloudEurekaServerA:8761/eureka,http://binbinCloudEurekaServerB:8762/eureka
  instance:
    #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经 过实验都是ip）
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
